#!/bin/bash
ocamllex lexer.mll
ocamlopt -o lexer lexer.ml
menhir -v minicparser.mly
ocamlc -c minicparser.mli
ocamllex miniclexer.mll
ocamlopt -o minicc_aux minic.ml minicparser.ml miniclexer.ml type.ml minicc.ml
